"use client";

import { useSearchParams, useRouter } from "next/navigation";
import { ArrowLeft, Printer, FileText, Download } from "lucide-react";
import { Button } from "@/components/ui/Button";
import Link from "next/link";

export default function FilePreviewPage({ params }: { params: { slug: string } }) {
  const searchParams = useSearchParams();
  const router = useRouter();
  const viewAs = searchParams.get("viewAs");
  const isPreview = viewAs === "preview";

  // Mock document data mapping based on ID/Slug
  const getDocumentType = (slug: string) => {
    if (slug.startsWith("f1")) return "Paperwork / Measurement Sheet";
    if (slug.includes("Q-")) return "Quotation";
    if (slug.includes("INV-")) return "Invoice";
    return "Generated Document";
  };

  const docType = getDocumentType(params.slug);

  return (
    <div className="min-h-screen bg-muted/30 p-4 md:p-8">
      <div className="max-w-5xl mx-auto space-y-6">
        {/* Navigation Header */}
        <div className="flex items-center justify-between print:hidden">
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="sm" onClick={() => router.back()}>
              <ArrowLeft className="h-4 w-4 mr-2" /> Back
            </Button>
            <h1 className="text-xl font-bold tracking-tight">{docType} Preview</h1>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={() => window.print()}>
              <Printer className="h-4 w-4 mr-2" /> Print
            </Button>
            <Button size="sm">
              <Download className="h-4 w-4 mr-2" /> Download
            </Button>
          </div>
        </div>

        {/* Document Container */}
        <div className={`
          bg-card text-foreground shadow-2xl rounded-2xl overflow-hidden mx-auto
          ${isPreview ? 'max-w-4xl' : 'w-full'}
          transition-all duration-500
        `}>
          {/* Mock Document Content */}
          <div className="p-12 md:p-20 flex flex-col min-h-[800px]">
            <div className="flex justify-between items-start mb-16 border-b border-border pb-10">
              <div>
                <h2 className="text-4xl font-black tracking-tighter text-accent uppercase mb-2">GMB Systems</h2>
                <p className="text-muted-foreground text-sm">Curtain & Blind Professionals</p>
              </div>
              <div className="text-right">
                <p className="font-bold text-lg uppercase tracking-wider">{docType}</p>
                <p className="text-muted-foreground text-sm uppercase tracking-widest mt-1">REF: {params.slug}</p>
                <p className="text-muted-foreground text-xs mt-4 italic">Generated on Oct 14, 2026</p>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-20 mb-16">
              <div className="space-y-4">
                <p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground border-b border-border pb-1">Billed To</p>
                <div>
                  <p className="font-bold text-lg">Global Offices Pty Ltd</p>
                  <p className="text-sm text-muted-foreground leading-relaxed mt-2">
                    123 Business Avenue<br />
                    Industrial Park, NSW 2000<br />
                    Australia
                  </p>
                </div>
              </div>
              <div className="space-y-4">
                <p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground border-b border-border pb-1">Project Details</p>
                <div>
                  <p className="font-bold text-lg">Holland Block Out Installation</p>
                  <p className="text-sm text-muted-foreground leading-relaxed mt-2">
                    Status: Approved<br />
                    Manager: Kiru<br />
                    PO: #88219
                  </p>
                </div>
              </div>
            </div>

            <div className="flex-1">
              <div className="flex items-center gap-3 mb-8 bg-muted/30 p-4 rounded-xl">
                 <FileText className="h-6 w-6 text-accent" />
                 <p className="text-sm font-medium">Digital Preview generated by GMB Cloud Paperwork Engine</p>
              </div>
              
              <div className="space-y-8 animate-pulse">
                <div className="h-4 bg-muted rounded w-full"></div>
                <div className="h-4 bg-muted rounded w-3/4"></div>
                <div className="h-4 bg-muted rounded w-5/6"></div>
                <div className="space-y-4 pt-10">
                   <div className="h-20 bg-muted/50 rounded-xl "></div>
                   <div className="h-20 bg-muted/50 rounded-xl "></div>
                   <div className="h-20 bg-muted/50 rounded-xl "></div>
                </div>
              </div>
            </div>

            <div className="mt-20 border-t border-border pt-10 text-center">
              <p className="text-xs text-muted-foreground uppercase tracking-widest">
                Professional Quality • Precision Measured • GMB Standard
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
